# Generated by Django 4.0.6 on 2022-08-01 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_proposal',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_and_product_desc',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_image',
            field=models.ImageField(null=True, upload_to='company_image'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='competitors_and_competative_advantage',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='market_size',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='marketing_plan',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='preposition',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='problem_desc',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='revenue_model',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='team_and_background_desc',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
