# Generated by Django 4.0.6 on 2022-08-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
